name: Lint

on:
  pull_request: {}

jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: File permissions
        if: always()
        run: "! grep -Ev '^644' <(git ls-files src/ tests/ | xargs stat '--format=%a %n')"
      - name: File encodings
        if: always()
        run: "! grep -E -e 'UTF-[^8]' -e 'UTF-[^ ]+ \\(with BOM\\)' <(git ls-files src/ tests/ | xargs stat '--format=%a %n')"
      - name: Line terminators
        if: always()
        run: "! grep 'with CRLF line terminators' <(git ls-files | file -nNf-)"
      - name: No unicode bidirectional control characters
        if: always()
        run: "! git grep -EIn $'[\\u2066\\u2067\\u2068\\u2069\\u202A\\u202B\\u202C\\u202D\\u202E]'"

  style:
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install Python dependencies
        run: >
          python -m pip install -U
          -e .
          --group lint
      - name: ruff check
        if: always()
        run: >
          python -m ruff check .
      - name: ruff format
        if: always()
        run: >
          python -m ruff format --diff .

  typing:
    name: Typing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install Python dependencies
        run: >
          python -m pip install -U
          -e .
          --group typing
      - name: mypy
        if: always()
        run: >
          python -m mypy --no-incremental
      - name: mypy docs
        if: always()
        run: >
          python -m mypy --no-incremental
