name: Update user agents

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-user-agents:
    if: github.repository == 'streamlink/streamlink'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python -m pip install requests
      - run: python ./script/update-user-agents.py
        env:
          WHATISMYBROWSER_API_KEY: ${{ secrets.WHATISMYBROWSER_API_KEY }}
      - uses: peter-evans/create-pull-request@6d9c0cdf5825c01278b6e63a0788434e6b3c5e27
        with:
          token: ${{ secrets.STREAMLINKBOT_USERAGENTS_PR }}
          add-paths: |
            src/streamlink/plugin/api/useragents.py
          commit-message: "plugin.api: update useragents"
          committer: "streamlinkbot <streamlinkbot@users.noreply.github.com>"
          author: "streamlinkbot <streamlinkbot@users.noreply.github.com>"
          branch: "automated/plugin/api/useragents"
          branch-suffix: timestamp
          delete-branch: true
          title: "plugin.api: update useragents"
          body: "Automated pull request"
